Update Install Poetry  command line (#26)
* Update Poetry command line

Now to install Poetry, we need to replace " get-poetry.py"  by  "install-poetry.py".
Otherwise it return  this error:

  File "<stdin>", line 1
    404: Not Found
    ^
SyntaxError: illegal target for annotation

* Update README.md

Co-authored-by: Leo Singer <leo.p.singer@nasa.gov>

---------

Co-authored-by: Leo Singer <leo.p.singer@nasa.gov>