Update Poetry command line
Now to install Poetry, we need to replace " get-poetry.py"  by  "install-poetry.py".
Otherwise it return  this error:

  File "<stdin>", line 1
    404: Not Found
    ^
SyntaxError: illegal target for annotation